music_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resource :session
  resources :bands
end

music_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

music_app/app/models/band.rb
class Band < ApplicationRecord
    validates :name, presence: true

    
end

music_app/app/models/user.rb
class User < ApplicationRecord
    attr_reader :password
    validates :email, :password_digest, presence: true
    validates :session_token, presence: true, uniqueness: true
    before_validation :ensure_session_token

    def self.generate_session_token
        self.session_token ||= SecureRandom::urlsafe_base64
    end

    def self.find_by_credentials(email, password)
        user = User.find_by(email: email)
        if user && user.is_password?(password)
            return user
        else
            return nil
        end
    end

    def reset_session_token!
        self.session_token = SecureRandom::urlsafe_base64
        self.save!
        self.session_token
    end

    def ensure_session_token
        self.session_token ||= SecureRandom::urlsafe_base64
    end

    def password=(password)
        self.password_digest = BCrypt::Password.create(password)
        @password = password
    end

    def is_password?(password)
        password_obj = BCrypt::Password.new(self.password_digest)
        password_obj.is_password?(password)
    end
end

music_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?

    def login!(user)
        session[:session_token] =user.reset_session_token
    end
    def logout
        current_user.reset_session_token! if logged_in?
        session[:session_token] = nil
        @current_user = nil
    end
    def current_user
        @current_user ||= User.find_by(session_token: session[:session_token])
    end
    def logged_in?
        !!current_user
    end
    def require_logged_in
        redirect_to  unless logged_in?
    end
    def require_logged_out
        redirect_to users_url if logged_in?
    end
end

music_app/app/controllers/bands_controller.rb
class BandsController < ApplicationController
    def index
        @bands = Band.all
        render :index
    end
    def new
        @band = Band.new
        render :new
    end
    def create
        band = Band.new(band_params)
        if band.save
        end
    end
end

music_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
        @user = User.new
        render :new
    end
    def create
        @user = User.find_by_credentials(params[:user][:email], params[:user][:password])
        if @user
            login!(@user)
            redirect_to user_url(@user)
        else
            @user = User.new
            render :new
        end
    end
    def destroy
        logout!
        redirect_to new_session_url
    end
end

music_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @users = User.all
        render :index
    end
    def new
        @user = User.new
        render :new
    end
    def create
        user = User.new(user_params)
        if user.save
            login!(user)
            redirect_to user_url(user)
        else
            render :new
        end
    end
    def show
        @user = User.find(params[:id])
        render :show
    end

    private
    def user_params
        params.require(:users).permit(:email, :password)
    end
end

music_app/app/helpers/application_helper.rb
module ApplicationHelper
end

music_app/app/helpers/bands_helper.rb
module BandsHelper
end

music_app/app/helpers/sessions_helper.rb
module SessionsHelper
end

music_app/app/helpers/users_helper.rb
module UsersHelper
end

music_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if logged_in? %>
      <h2>Welcome</h2>
    <% else %>
      <a href="<%= new_session_url %>">Log In</a>
      <a href="<%= new_user_url %>">Sign Up</a>
    <% end %>
    <%= yield %>
  </body>
</html>

music_app/app/views/users/index.html.erb
<h1>Everyone's here, it's a party!</h1>

<ul>
    <% @users.each do |user| %>
    <li>
        <%= user.email %>
    </li>
    <% end %>
</ul>

music_app/app/views/users/new.html.erb
<h1>Create an account</h1>

<form action=" <%= users_url %> " method="POST" >
    <label for="email">E-Mail
        <input type="text" name="user[email]" id="email" value=" <%= @user.email %> ">
    </label>

    <label for="password">Password
        <input type="password" name="user[password]" id="password" value=" <%= @user.password %> ">
    </label>

    <button>Create Account</button>
</form>

music_app/app/views/users/show.html.erb
<h2>Welcome! You've logged in :)</h2>